server:
  port: 8080
spring:
  h2:
    console:
      path: /console
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

   